regression_metric:
  class_path: comet.models.RegressionMetric
  init_args:
    nr_frozen_epochs: 0
    keep_embeddings_frozen: True
    optimizer: AdamW
    encoder_learning_rate: 1e-4
    learning_rate: 1e-3
    layerwise_decay: 0.95
    encoder_model: mT5_encdec
    pretrained_model: google/mt5-small
    pool: cls
    layer: mix
    layer_transformation: sparsemax
    layer_norm: False
    loss: mse
    dropout: 0.1
    batch_size: 8
    train_data: 
      - data/1718-da.csv
    validation_data: 
      - data/wmt-2019-da.csv
    hidden_sizes:
      - 3072
      - 1024
    activations: Tanh
    
trainer: ../mt5_trainer.yaml
early_stopping: ../early_stopping.yaml
model_checkpoint: ../mt5_encdec_fast_model_checkpoint.yaml
