regression_metric:
  class_path: comet.models.RegressionMetric
  init_args:
    nr_frozen_epochs: 0
    keep_embeddings_frozen: True
    optimizer: AdamW
    encoder_learning_rate: 1.0e-06
    learning_rate: 1.5e-05
    layerwise_decay: 1
    encoder_model: Canine
    pretrained_model: google/canine-c
    pool: avg
    layer: 16
    layer_transformation: sparsemax
    layer_norm: False
    loss: mse
    dropout: 0.1
    batch_size: 4
    train_data: 
      - data/1718-da.csv
    validation_data: 
      - data/wmt-2019-da.csv
    hidden_sizes:
      - 3072
      - 1024
    activations: Tanh
    
trainer: ../canine-c_trainer.yaml
early_stopping: ../early_stopping.yaml
model_checkpoint: ../canine-c_model_checkpoint-big_estimator.yaml
