regression_metric:
  class_path: comet.models.RegressionMetric
  init_args:
    nr_frozen_epochs: 0
    keep_embeddings_frozen: True
    optimizer: AdamW
    encoder_learning_rate: 1.0e-06
    learning_rate: 1.5e-05
    layerwise_decay: 1
    encoder_model: mbert
    pretrained_model: bert-base-multilingual-cased
    pool: avg
    layer: 12
    layer_transformation: sparsemax
    layer_norm: False
    loss: mse
    dropout: 0.1
    batch_size: 8
    train_data: 
      - data/1718-da.csv
    validation_data: 
      - data/wmt-2019-da.csv
    hidden_sizes:
      - 1536
      - 768
    activations: Tanh
    
trainer: ../mbert_trainer.yaml
early_stopping: ../early_stopping.yaml
model_checkpoint: ../mbert_model_checkpoint.yaml
